### ISSUE TITLE
what should be I fill in `fillOpacity`?

### ISSUE THREAD

**Issue by chenzhutian** [ethantran/react-native-examples#7]
According to the [article](https://medium.com/@ethantran/animating-svg-in-react-native-cf1907831608), I should fill the string type in the `fillOpacity`.
![image](https://user-images.githubusercontent.com/3315274/35918509-06be9530-0c4d-11e8-8d1f-bd7ad9278d59.png)
However, I get this error:
![image](https://user-images.githubusercontent.com/3315274/35918526-14398490-0c4d-11e8-85ea-6fdabc9a3552.png)

But if I change the ouput value to number type,
![image](https://user-images.githubusercontent.com/3315274/35918553-2e276f8e-0c4d-11e8-90c3-f37220d8dcb5.png)
it shows me another value says NSNumber cannot be converted to NSString.
![image](https://user-images.githubusercontent.com/3315274/35918593-501a7db6-0c4d-11e8-8168-71229a14d2da.png)

So what should I do to fix this issue?

**Comment by ethantran** [comment]
Hey. Did you do `toString()` to the value in `setNativeProps`? For some reason, strokeWidth, strokeOpacity, and fillOpacity require that. You should have something that looks like  https://github.com/ethantran/react-native-examples/blob/0497ec4475c16e967a6189558b19eba8ecea0526/src/components/AnimatedSvgPropStringFix.js#L15-L24

**Comment by chenzhutian** [comment]
Yes I do.
Actually I use the component from you, 
https://github.com/ethantran/react-native-examples/blob/master/src/components/AnimatedSvgCircle.js

BTW, thanks for your great job.

**Comment by ethantran** [comment]
Oh thanks I see a bug, try changing `propKeys` to `this.propKeys` on line 16.  That should fix it, but I can't test right now to make sure.

**Comment by chenzhutian** [comment]
I think that's the bug. I will test soon. Thanks for your reply.
Close this issue.

**Comment by ethantran** [comment]
Never mind, that is not a bug. I am not sure why it doesn't work. Take a look at `SvgBrushAnimation.js` for an example on how to use `fillOpacity`. I've updated the example with circle and it works.
  https://github.com/ethantran/react-native-examples/blob/master/src/screens/SvgBrushAnimation.js
